### ISSUE TITLE
GLaBIOS is not working

### ISSUE THREAD

**Issue by andreas-jonsson** [andreas-jonsson/virtualxt#28]
Booting with [GLaBIOS](https://github.com/640-KB/GLaBIOS) should work!
It gets stuck testing the timers. If the debugger is used to skip the test we get a picture at least.

One issue is already fixed [here](https://github.com/andreas-jonsson/virtualxt/commit/638e4ee2f6119f983d9bf4cf2c6e229cf696d9ed#commitcomment-89297973).

**Comment by andreas-jonsson** [comment]
Got this kinda working.
It boots to DOS at least. :)

Thanks to @640-KB for creating this awesome BIOS!

**Comment by 640-KB** [comment]
> Got this kinda working. It boots to DOS at least. :)
> 
> Thanks to @640-KB for creating this awesome BIOS!

That's great to hear!  So, it's "kinda" working?  What isn't working?  Anything I can do to help?

**Comment by andreas-jonsson** [comment]
Hi! Yea.

I have some issues with the CRT cursor and the FDC but I'm quite sure I know what the problems are with those.

But I also get this 4000 error and 'KB' printed out.
![image](https://user-images.githubusercontent.com/4725590/204827624-1577e81b-de86-4746-80f7-0fb5e2b3dcf0.png)
What is Error: 4000?

**Comment by 640-KB** [comment]
> Hi! Yea.
> 
> I have some issues with the CRT cursor and the FDC but I'm quite sure I know what the problems are with those.

Do tell!  Wild guesses, does it have to do with using WORD size `OUT  DX, AX` to write to the two adjacent ports?  And does the FDC have to do with doing a `HLT` waiting for the interrupt from the FDC?  I found I could eke out a tiny performance improvement doing that and have been surprised that it's actually worked on everything I've ever tested (except the FDC thing on one outlier motherboard so I did put in a build switch to not do that).

> But I also get this 4000 error and 'KB' printed out. ![image](https://user-images.githubusercontent.com/4725590/204827624-1577e81b-de86-4746-80f7-0fb5e2b3dcf0.png) What is Error: 4000?

That's where it sends a reset command to the keyboard controller and expects an IRQ1 with a "reset okay" code (`0AAh`) to happen during a timeout period (65536 LOOPs)... step 3 of this: https://minuszerodegrees.net/5160/keyboard/5160_keyboard_startup.jpg.  In theory this is what would generate a 301 error on an IBM BIOS (would be curious if that does that on virtualxt or not!).

Here it is in the code: https://github.com/andreas-jonsson/virtualxt/blob/6efd2a32389a08c3085e50d5b2ba09af013d3896/bios/glabios.asm#L2580

I actually did add a build time switch (`POST_TEST_KB = 0`) in the 0.2.0 version since it also doesn't succeed on some other projects that use a different KB controller (ex: EMM Homebrew 8088 using an 8042).  So that is an option too (though you wouldn't be using the "official version" :) ).

**Comment by andreas-jonsson** [comment]
- Cursor
Yes.. ;)

- FDC
It is just not fully implemented. I'm currently relying on a BIOS extension for disk access.

The keyboard reset and CRT cursor is fixed in the develop/edge branch.
I have included GLaBIOS in the builds so the users can switch if they prefer.  Perhaps I will switch to use it as default once the FDC is fully working.

Thanks for the help!
