### ISSUE TITLE
Keyboard barely usable

### ISSUE THREAD

**Issue by fmahnke** [andreas-jonsson/virtualxt#33]
The FreeDOS keyboard input is barely usable for me with `df256e`. I get missed characters and duplicated characters when typing at a normal (fast) speed. I can get work done by typing very slowly and repeating characters if they don't echo at the prompt. See attached screenshot and text file with standard output.

I was trying to type "c:", then "cd games".

Steps to reproduce:

```
zig build
./build/bin/virtualxt
```

Then do some fast typing at the FreeDOS prompt.

This doesn't seem to be specific to FreeDOS. I get a similar result testing my own OS image.

I also noticed that left shift is acting as a shift lock. After pressing it, all characters are caps, but all numbers are also shifted to symbols. Pressing left shift again releases shift lock. Not sure if this is expected or not.

Possibly related to https://github.com/andreas-jonsson/virtualxt/issues/21?

![2023-02-06-122429_1076x617_scrot](https://user-images.githubusercontent.com/610099/217066111-d88cdf3f-5e55-4d4e-8723-6fa109a1b1c5.png)
[bug.txt](https://github.com/andreas-jonsson/virtualxt/files/10668528/bug.txt)

**Comment by fmahnke** [comment]
I bisected and the missed/dropped/duplicated characters problem seems to come with https://github.com/andreas-jonsson/virtualxt/commit/bd158132174939a096bdc4ae94ad88950d43cb97

I can't reproduce the shift lock behavior right now.

**Comment by andreas-jonsson** [comment]
I need to debug this a bit more. I cant immediately reproduce it on my machine.

One possible issue I can think of is if you are loading VXTDRV.COM. The driver will cause an error when you type things on the screen. (It writes to a port that is no longer mapped and that causes logging) This can be fixed by recompiling the driver... its on my TODO list.

**Comment by andreas-jonsson** [comment]
Possible related #21

**Comment by andreas-jonsson** [comment]
Can you confirm that you are building with `-Drelease-fast`?

There was a significant change in Zig v 0.10 when they moved to a self hosting compiler that causes the `release-safe` option to be very slow for VirtualXT. I have not investigated this further but if this behavior persists in the next Zig release I might consider changing the default option. On my machine it is usable but I can tell the text input is a bit sluggish.

**Comment by fmahnke** [comment]
I'm not intentionally loading VXTDRV.com, but I'll investigate around that.

I just build with `-Drelease-fast` and don't see the issue there. This is the first I've worked with Zig before, and I admit I don't really know anything about it except what I've gleaned from reading the `build.zig` file. I'll read the docs on the Zig web site in the next few days.

**Comment by andreas-jonsson** [comment]
You should not have to read up on Zig in order to use VirtualXT. Admittedly the defaults should just work.
I will keep this issue open until I either find out why the optimization level has the dramatic impact it does or I change the defaults. (It will be interesting to see if this behavior persists even in Zig 0.11.)

**Comment by andreas-jonsson** [comment]
This is a problem that will go away with #39
